version: '3.5'
services:
  zkevm-bridge-ui:
    container_name: zkevm-bridge-ui
    image: hermeznetwork/zkevm-bridge-ui:latest
    ports:
      - 8080:80
    environment:
      - ETHEREUM_RPC_URL=$ZKEVM_NODE_ETHERMAN_URL
      - ETHEREUM_EXPLORER_URL=http://zkevm-explorer-l1:4000
      - ETHEREUM_BRIDGE_CONTRACT_ADDRESS=0xff0EE8ea08cEf5cb4322777F5CC3E8A584B8A4A0
      - ETHEREUM_FORCE_UPDATE_GLOBAL_EXIT_ROOT=true
      - ETHEREUM_PROOF_OF_EFFICIENCY_CONTRACT_ADDRESS=0x610178dA211FEF7D417bC0e6FeD39F05609AD788
      - POLYGON_ZK_EVM_RPC_URL=http://zkevm-json-rpc:8123
      - POLYGON_ZK_EVM_EXPLORER_URL=http://zkevm-explorer-l2:4001
      - POLYGON_ZK_EVM_BRIDGE_CONTRACT_ADDRESS=0xff0EE8ea08cEf5cb4322777F5CC3E8A584B8A4A0
      - POLYGON_ZK_EVM_NETWORK_ID=1
      - BRIDGE_API_URL=http://zkevm-bridge-service:8080
      - ENABLE_FIAT_EXCHANGE_RATES=false
      - ENABLE_OUTDATED_NETWORK_MODAL=false
      - ENABLE_DEPOSIT_WARNING=true
      - ENABLE_REPORT_FORM=false
      
